-- =============================================================================
-- V14: Drop stale report_definition_repository table
-- This join table was auto-generated by Hibernate in an earlier schema version
-- and is no longer used. Its foreign key prevents deleting report definitions.
-- =============================================================================

DROP TABLE IF EXISTS report_definition_repository;
